all:
	(cd coproc0 ; make)
	(cd loader ; make)
	(cd mmu ; make)
	(cd rbtree0 ; make)
	(cd rbtree1 ; make)
	(cd serial0 ; make)
	(cd serial1 ; make)
	(cd serial2 ; make)
	(cd timer0 ; make)
	(cd timer1 ; make)

clean:
	(cd coproc0 ; make clean)
	(cd loader ; make clean)
	(cd mmu ; make clean)
	(cd rbtree0 ; make clean)
	(cd rbtree1 ; make clean)
	(cd serial0 ; make clean)
	(cd serial1 ; make clean)
	(cd serial2 ; make clean)
	(cd timer0 ; make clean)
	(cd timer1 ; make clean)

